`define RFREG_NUM	32
`define XLEN        32
`define FLEN        32
`define RFIDX_WIDTH 5
`define PC_SIZE     32
`define INSTR_SIZE  32
`define DECINFO_WIDTH       33

`define DECINFO_GRP_WIDTH   3

`define DECINFO_GRP_ALU     `DECINFO_GRP_WIDTH'd0

`define DECINFO_GRP_LSB     0
`define DECINFO_GRP_MSB     (`DECINFO_GRP_LSB+`DECINFO_GRP_WIDTH-1)
`define DECINFO_GRP         `DECINFO_GRP_MSB:`DECINFO_GRP_LSB
`define DECINFO_RV32_LSB    (`DECINFO_GRP_MSB+1)
`define DECINFO_RV32_MSB    (`DECINFO_RV32_LSB+1-1)
`define DECINFO_RV32        `DECINFO_RV32_MSB:`DECINFO_RV32_LSB

`define DECINFO_SUBDECINFO_LSB  (`DECINFO_RV32_MSB+1)

`define DECINFO_ALU_ADD_LSB    		`DECINFO_SUBDECINFO_LSB
`define DECINFO_ALU_ADD_MSB    		(`DECINFO_ALU_ADD_LSB+1-1)
`define DECINFO_ALU_ADD    			`DECINFO_ALU_ADD_MSB :`DECINFO_ALU_ADD_LSB 
`define DECINFO_ALU_SUB_LSB    		(`DECINFO_ALU_ADD_MSB+1)
`define DECINFO_ALU_SUB_MSB    		(`DECINFO_ALU_SUB_LSB+1-1)
`define DECINFO_ALU_SUB    			`DECINFO_ALU_SUB_MSB :`DECINFO_ALU_SUB_LSB 
`define DECINFO_ALU_XOR_LSB    		(`DECINFO_ALU_SUB_MSB+1)
`define DECINFO_ALU_XOR_MSB    		(`DECINFO_ALU_XOR_LSB+1-1)
`define DECINFO_ALU_XOR    			`DECINFO_ALU_XOR_MSB :`DECINFO_ALU_XOR_LSB 
`define DECINFO_ALU_SLL_LSB    		(`DECINFO_ALU_XOR_MSB+1)
`define DECINFO_ALU_SLL_MSB    		(`DECINFO_ALU_SLL_LSB+1-1)
`define DECINFO_ALU_SLL    			`DECINFO_ALU_SLL_MSB :`DECINFO_ALU_SLL_LSB 
`define DECINFO_ALU_SRL_LSB    		(`DECINFO_ALU_SLL_MSB+1)
`define DECINFO_ALU_SRL_MSB    		(`DECINFO_ALU_SRL_LSB+1-1)
`define DECINFO_ALU_SRL    			`DECINFO_ALU_SRL_MSB :`DECINFO_ALU_SRL_LSB 
`define DECINFO_ALU_SRA_LSB    		(`DECINFO_ALU_SRL_MSB+1)
`define DECINFO_ALU_SRA_MSB    		(`DECINFO_ALU_SRA_LSB+1-1)
`define DECINFO_ALU_SRA    			`DECINFO_ALU_SRA_MSB :`DECINFO_ALU_SRA_LSB 
`define DECINFO_ALU_OR_LSB    		(`DECINFO_ALU_SRA_MSB+1)
`define DECINFO_ALU_OR_MSB    		(`DECINFO_ALU_OR_LSB+1-1)
`define DECINFO_ALU_OR     			`DECINFO_ALU_OR_MSB  :`DECINFO_ALU_OR_LSB  
`define DECINFO_ALU_AND_LSB    		(`DECINFO_ALU_OR_MSB+1)
`define DECINFO_ALU_AND_MSB    		(`DECINFO_ALU_AND_LSB+1-1)
`define DECINFO_ALU_AND    			`DECINFO_ALU_AND_MSB :`DECINFO_ALU_AND_LSB 
`define DECINFO_ALU_SLT_LSB    		(`DECINFO_ALU_AND_MSB+1)
`define DECINFO_ALU_SLT_MSB    		(`DECINFO_ALU_SLT_LSB+1-1)
`define DECINFO_ALU_SLT    			`DECINFO_ALU_SLT_MSB :`DECINFO_ALU_SLT_LSB 
`define DECINFO_ALU_SLTU_LSB    	(`DECINFO_ALU_SLT_MSB+1)
`define DECINFO_ALU_SLTU_MSB    	(`DECINFO_ALU_SLTU_LSB+1-1)
`define DECINFO_ALU_SLTU   			`DECINFO_ALU_SLTU_MSB:`DECINFO_ALU_SLTU_LSB
`define DECINFO_ALU_LUI_LSB    		(`DECINFO_ALU_SLTU_MSB+1)
`define DECINFO_ALU_LUI_MSB    		(`DECINFO_ALU_LUI_LSB+1-1)
`define DECINFO_ALU_LUI    			`DECINFO_ALU_LUI_MSB :`DECINFO_ALU_LUI_LSB 
`define DECINFO_ALU_OP2IMM_LSB    	(`DECINFO_ALU_LUI_MSB+1)
`define DECINFO_ALU_OP2IMM_MSB    	(`DECINFO_ALU_OP2IMM_LSB+1-1)
`define DECINFO_ALU_OP2IMM    		`DECINFO_ALU_OP2IMM_MSB :`DECINFO_ALU_OP2IMM_LSB 
`define DECINFO_ALU_OP1PC_LSB    	(`DECINFO_ALU_OP2IMM_MSB+1)
`define DECINFO_ALU_OP1PC_MSB    	(`DECINFO_ALU_OP1PC_LSB+1-1)
`define DECINFO_ALU_OP1PC    		`DECINFO_ALU_OP1PC_MSB :`DECINFO_ALU_OP1PC_LSB 
`define DECINFO_ALU_NOP_LSB    		(`DECINFO_ALU_OP1PC_MSB+1)
`define DECINFO_ALU_NOP_MSB    		(`DECINFO_ALU_NOP_LSB+1-1)
`define DECINFO_ALU_NOP    			`DECINFO_ALU_NOP_MSB :`DECINFO_ALU_NOP_LSB 
`define DECINFO_ALU_ECAL_LSB  		(`DECINFO_ALU_NOP_MSB+1)
`define DECINFO_ALU_ECAL_MSB  		(`DECINFO_ALU_ECAL_LSB+1-1)
`define DECINFO_ALU_ECAL   			`DECINFO_ALU_ECAL_MSB:`DECINFO_ALU_ECAL_LSB 
`define DECINFO_ALU_EBRK_LSB  		(`DECINFO_ALU_ECAL_MSB+1)
`define DECINFO_ALU_EBRK_MSB  		(`DECINFO_ALU_EBRK_LSB+1-1)
`define DECINFO_ALU_EBRK   			`DECINFO_ALU_EBRK_MSB:`DECINFO_ALU_EBRK_LSB 
`define DECINFO_ALU_WFI_LSB  		(`DECINFO_ALU_EBRK_MSB+1)
`define DECINFO_ALU_WFI_MSB  		(`DECINFO_ALU_WFI_LSB+1-1)
`define DECINFO_ALU_WFI   			`DECINFO_ALU_WFI_MSB:`DECINFO_ALU_WFI_LSB 

`define DECINFO_ALU_WIDTH    		(`DECINFO_ALU_WFI_MSB+1)

`define ALU_ADDER_WIDTH     (`XLEN+1)
